name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.402'
      - name: Build with dotnet
        run: dotnet build src/NopCommerce.sln
      - name: InferSharp
        uses: microsoft/infersharpaction@v0.2
        id: runinfersharp
        with:
          binary-path: './src/Presentation/Nop.Web/bin/Debug/netcoreapp3.1'
          report-on-files: 'src/Libraries/Nop.Services/Catalog/ProductService.cs'
      - name: Infer# analysis results
        run: echo "${{ steps.runinfersharp.outputs.results }}"
